app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(doLayout = "springy")
app$snapshot()
app$setInputs(fit = "click")
app$snapshot()
app$setInputs(fitSelected = "click")
app$snapshot()
app$setInputs(sfn = "click")
app$setInputs(fit = "click")
app$snapshot()
app$setInputs(addRandomGraphFromDataFramesButton = "click")
app$snapshot()
app$setInputs(doLayout = "fcose")
app$snapshot()
