app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(newPlotButton = "click")
app$snapshot()
app$setInputs(newPlotButton = "click")
app$snapshot()
app$setInputs(newPlotButton = "click")
app$snapshot()
